### ISSUE TITLE
Type error: Return value of CacheKey::getValuesFromWhere() must be of the type string, array returned

### ISSUE THREAD

**Issue by eelco2k** [GeneaLabs/laravel-model-caching#136]
# Issue
Type error: Return value of CacheKey::getValuesFromWhere() must be of the type string, array returned

## Environment
Laravel Version: 5.5.40
Laravel Model Caching Package Version: 0.2.61
PHP Version: PHP 7.2.4-1+b2 (cli) (built: May 29 2018 02:53:13) ( NTS )

Operating System & Version: Debian old-sid

## Stack Trace

```
Type error: Return value of GeneaLabs\LaravelModelCaching\CacheKey::getValuesFromWhere() must be of the type string, array returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Return value of GeneaLabs\\LaravelModelCaching\\CacheKey::getValuesFromWhere() must be of the type string, array returned at ./vendor/genealabs/laravel-model-caching/src/CacheKey.php:127

[stacktrace]
#0 ./vendor/genealabs/laravel-model-caching/src/CacheKey.php(113): GeneaLabs\\LaravelModelCaching\\CacheKey->getValuesFromWhere(Array)
#1 ./vendor/genealabs/laravel-model-caching/src/CacheKey.php(255): GeneaLabs\\LaravelModelCaching\\CacheKey->getValuesClause(Array)
#2 ./vendor/genealabs/laravel-model-caching/src/CacheKey.php(155): GeneaLabs\\LaravelModelCaching\\CacheKey->getOtherClauses(Array, NULL)
#3 [internal function]: GeneaLabs\\LaravelModelCaching\\CacheKey->GeneaLabs\\LaravelModelCaching\\{closure}(NULL, Array)
#4 ./vendor/laravel/framework/src/Illuminate/Support/Collection.php(1228): array_reduce(Array, Object(Closure), NULL)
#5 ./vendor/genealabs/laravel-model-caching/src/CacheKey.php(158): Illuminate\\Support\\Collection->reduce(Object(Closure))
#6 ./vendor/genealabs/laravel-model-caching/src/CacheKey.php(36): GeneaLabs\\LaravelModelCaching\\CacheKey->getWhereClauses()
#7 ./vendor/genealabs/laravel-model-caching/src/Traits/Caching.php(76): GeneaLabs\\LaravelModelCaching\\CacheKey->make(Array, NULL, '-count')
#8 ./vendor/genealabs/laravel-model-caching/src/CachedBuilder.php(33): GeneaLabs\\LaravelModelCaching\\CachedBuilder->makeCacheKey(Array, NULL, '-count')
#9 ./app/Models/Klager.php(679): GeneaLabs\\LaravelModelCaching\\CachedBuilder->count()


```

**Comment by mikebronner** [comment]
Hi @eelco2k, could you please include the eloquent query that caused this error? That will help me recreate the problem and fix it. Thanks!

**Comment by eelco2k** [comment]
hi @mikebronner,

Here is my eloquent query:

```
$klager_active = \App\Models\Klager::ModelJoin('postcd')
                            ->where('achternaam', '=', $data['naam'])
                            ->where('postcd.postcode', '=', $data['postcode'])
                            ->where('postcd.huisnr', '=', $data['huisnr'])
                            ->where('postcd.toevoeging', '=', $data['toevoeging'])
                            ->where('active', '=', 0);
$count = $klager_active->count() ;
```
in my Klager model i have setup this ModelJoin scope function:

```

/**
     * Scope a query to include a other relation model.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */

    public function scopeModelJoin($query, $relation_name, $operator = '=', $type = 'left', $where = false) {
        $relation = $this->$relation_name();
        $table = $relation->getRelated()->getTable();
        $one = $relation->getQualifiedParentKeyName();
        $two = $relation->getQualifiedForeignKeyName();

        if (empty($query->columns)) {
            $query->select($this->getTable().".*");
        }

        //$join_alias = $table;
        $prefix = $query->getQuery()->getGrammar()->getTablePrefix();
        $join_alias = $relation_name;
        foreach (\Schema::getColumnListing($table) as $related_column) {
            $query->addSelect(\DB::raw("`$prefix$join_alias`.`$related_column` AS `$join_alias.$related_column`"));
        }
        $two = str_replace($table . ".", $join_alias . ".", $two);
        return $query->join("$table AS $prefix$relation_name", $one, $operator, $two, $type, $where); //->with($relation_name);
    }
```

**Comment by eelco2k** [comment]
strangely i tried today and the error is gone. maybe because of the 0.2.62 version update. I don't know.
will close for now.

**Comment by mikebronner** [comment]
Ah, very good ... the 0.2.62 update has been out for a few days now ... is it possible you didn't update until today? Glad to hear it's resolved :)

**Comment by eelco2k** [comment]
Unfortunately still happening but now on production server. I will debug further. maybe php version or specific config. i'm not sure...

**Comment by mikebronner** [comment]
Please provide the exact eloquent query and full stack trace for the new error on production.

**Comment by eelco2k** [comment]
@mikebronner It's the same eloquent as posted here above. the query which makes that eloquent model is: 
```
select * from `klager` left join `postcd` as `postcd` on `klager`.`postcd_id` = `postcd`.`id` where `active` = ? and `postcd`.`postalcode` = ? and `postcd`.number = ? and `postcd`.`addition` = ? and `klager`.`deleted_at` is null 
```

**Comment by eelco2k** [comment]
So in my \App\Models\Klager() Model i have a protected variable $filterable; and the Filterable Trait set.

```
<?php

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Gency\Filterable\Filterable;
use GeneaLabs\LaravelModelCaching\Traits\Cachable;

class Klager extends Model {

    use SoftDeletes;
    use \Gency\Filterable\FilterableTrait;
    use Cachable;

protected $filterable = [
        'id'                => Filterable::Integer,
        'active'            => Filterable::Boolean,
        'achternaam'        => Filterable::String,
        'created_at'        => Filterable::Date,
        'updated_at'        => Filterable::Date,
        'deleted_at'        => Filterable::Date
    ];

}

/* SCOPES */

    /**
     * Scope a query to include a other relation model.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */

    public function scopeModelJoin($query, $relation_name, $operator = '=', $type = 'left', $where = false) {
        $relation = $this->$relation_name();
        $table = $relation->getRelated()->getTable();
        $one = $relation->getQualifiedParentKeyName();
        $two = $relation->getQualifiedForeignKeyName();

        if (empty($query->columns)) {
            $query->select($this->getTable().".*");
        }

        //$join_alias = $table;
        $prefix = $query->getQuery()->getGrammar()->getTablePrefix();
        $join_alias = $relation_name;
        foreach (\Schema::getColumnListing($table) as $related_column) {
            $query->addSelect(\DB::raw("`$prefix$join_alias`.`$related_column` AS `$join_alias.$related_column`"));
        }
        $two = str_replace($table . ".", $join_alias . ".", $two);
        return $query->join("$table AS $prefix$relation_name", $one, $operator, $two, $type, $where); //->with($relation_name);
    }

?>
```

**Comment by eelco2k** [comment]
I also Logged the $wheres CacheKey.php line 127:

this is the result:

```
[2018-06-12 11:30:03] production.DEBUG: Cachable {"type":"Basic","column":"postcd.postcode","operator":"=","value":"8888AA","boolean":"and"}
[2018-06-12 11:30:03] production.DEBUG: Cachable {"type":"Basic","column":"postcd.huisnr","operator":"=","value":"55","boolean":"and"}
[2018-06-12 11:30:03] production.DEBUG: Cachable {"type":"Basic","column":"postcd.toevoeging","operator":"=","value":"D","boolean":"and"}
[2018-06-12 11:30:03] production.DEBUG: Cachable {"type":"Basic","column":"active","operator":"=","value":1,"boolean":"and"}
[2018-06-12 11:30:03] production.DEBUG: Cachable {"type":"Basic","column":"postcd.postcode","operator":"=","value":"8888AA","boolean":"and"}
[2018-06-12 11:30:03] production.DEBUG: Cachable {"type":"Basic","column":"postcd.huisnr","operator":"=","value":"55","boolean":"and"}
[2018-06-12 11:30:03] production.DEBUG: Cachable {"type":"Basic","column":"postcd.toevoeging","operator":"=","value":"D","boolean":"and"}
[2018-06-12 11:30:03] production.DEBUG: Cachable {"type":"Basic","column":"active","operator":"=","value":1,"boolean":"and"}
```

Looks normal....
But the line after this i get the error:
```
Type error: Return value of CacheKey::getValuesFromWhere() must be of the type string, array returned
```

**Comment by mikebronner** [comment]
@eelco2k Can you try removing filterable from your model and see if it still errors? I can't help debug 3rd-party packages, sorry, I just don't have enough time. I'm closing this issue for now, it has become too convoluted. If you see this happening without the filterable package installed, please submit a new issue that includes the eloquent query and the stack-trace. Thanks! :)

**Comment by fatonsopa** [comment]
Hi @mikebronner,

I was wondering if you were able to solve the issue, as it still happening on the latest version

`        $now = new \DateTime();
        
         //working
        $deals = Deal::where('saleStarts', '<=', '2018-11-28 11:30:41')->inRandomOrder()->get();

        //working
        $deals = Deal::where('saleStarts', '<=', $now)->inRandomOrder()->get();

        //not working
        $deals = Deal::where('saleStarts', '<=', $now)->get();

`


Error:
`Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Return value of GeneaLabs\LaravelModelCaching\CacheKey::getValuesFromWhere() must be of the type string, object returned`
