### ISSUE TITLE
production.ERROR: Return value of GeneaLabs\LaravelModelCaching\CacheKey::getValuesFromWhere() must be of the type string, array returned

### ISSUE THREAD

**Issue by kolirt** [GeneaLabs/laravel-model-caching#190]
help me. laravel gives me an unknown error

my settings

> "require": {
>         "php": "^7.1.3",
>         "buzz/laravel-google-captcha": "^2.1",
>         "cviebrock/eloquent-sluggable": "^4.5",
>         "fideloper/proxy": "^4.0",
>         "genealabs/laravel-model-caching": "^0.2.63",
>         "intervention/image": "^2.4",
>         "intervention/imagecache": "^2.3",
>         "laracasts/flash": "^3.0",
>         "laravel/framework": "5.6.*",
>         "laravel/socialite": "^3.0",
>         "laravel/tinker": "^1.0",
>         "laravelcollective/html": "^5.6",
>         "laravelium/sitemap": "2.8.*",
>         "lavary/laravel-menu": "^1.7",
>         "predis/predis": "^1.1",
>         "yajra/laravel-datatables-oracle": "^8.6"
>     },
>     "require-dev": {
>         "barryvdh/laravel-debugbar": "^3.1",
>         "barryvdh/laravel-ide-helper": "^2.4",
>         "doctrine/dbal": "^2.7",
>         "filp/whoops": "^2.0",
>         "fzaninotto/faker": "^1.4",
>         "mockery/mockery": "^1.0",
>         "nunomaduro/collision": "^2.0",
>         "phpunit/phpunit": "^7.0"
>     },

**Logs:**
```
[2018-11-19 12:31:38] production.ERROR: Return value of GeneaLabs\LaravelModelCaching\CacheKey::getValuesFromWhere() must be of the type string, array returned (View: /home/user/sites/site.php/www/resources/views/layouts/app.blade.php) (View: /home/user/sites/site.php/www/resources/views/layouts/app.blade.php) {"exception":"[object] (ErrorException(code: 0): Return value of GeneaLabs\\LaravelModelCaching\\CacheKey::getValuesFromWhere() must be of the type string, array returned (View: /home/user/sites/site.php/www/resources/views/layouts/app.blade.php) (View: /home/user/sites/site.php/www/resources/views/layouts/app.blade.php) at /home/user/sites/site.php/www/vendor/genealabs/laravel-model-caching/src/CacheKey.php:139, ErrorException(code: 0): Return value of GeneaLabs\\LaravelModelCaching\\CacheKey::getValuesFromWhere() must be of the type string, array returned (View: /home/user/sites/site.php/www/resources/views/layouts/app.blade.php) at /home/user/sites/site.php/www/vendor/genealabs/laravel-model-caching/src/CacheKey.php:139, Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of GeneaLabs\\LaravelModelCaching\\CacheKey::getValuesFromWhere() must be of the type string, array returned at /home/user/sites/site.php/www/vendor/genealabs/laravel-model-caching/src/CacheKey.php:139)
[stacktrace]
#0 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/home/user...', Array)
#2 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\\View\\Engines\\CompilerEngine->get('/home/user...', Array)
#3 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\\View\\View->getContents()
#4 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/View/View.php(90): Illuminate\\View\\View->renderContents()
#5 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#6 /home/user/sites/site.php/www/vendor/symfony/http-foundation/Response.php(202): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#7 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(733): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View))
#8 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#9 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#10 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /home/user/sites/site.php/www/app/Http/Middleware/FrontMiddleware.php(40): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\FrontMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#34 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#35 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#36 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#37 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#38 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/user/sites/site.php/www/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/user/sites/site.php/www/app/Http/Middleware/HttpsProtocol.php(32): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\HttpsProtocol->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/user/sites/site.php/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#62 /home/user/sites/site.php/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#63 /home/user/sites/site.php/www/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#64 {main}
"} 
```

**Comment by kolirt** [comment]
?

**Comment by mikebronner** [comment]
@kolirt To troubleshoot this, please provide **all** the information required in the issue template:

```
Describe the bug A clear and concise description of what the bug is.

Eloquent Query Please provide the complete eloquent query that caused the bug, for example:

$model->with('otherModel')->get();
Stack Trace The full stack trace from your log file.

Environment

PHP: [e.g. 7.1.0]
OS: [e.g. Ubuntu 18.04]
Laravel: [e.g. 5.6.15]
Model Caching: [e.g. 0.2.61]
Additional context Add any other context about the problem here.
```

**Comment by kolirt** [comment]
@mikebronner  I can not send this code. I do not know what causes this error. error occurs in production. there is nothing in the logs

**Comment by mikebronner** [comment]
Track down what is causing this error in your layout file:

```
[2018-11-19 12:31:38] production.ERROR: Return value of GeneaLabs\LaravelModelCaching\CacheKey::getValuesFromWhere() must be of the type string, array returned (View: /home/user/sites/site.php/www/resources/views/layouts/app.blade.php) (View: /home/user/sites/site.php/www/resources/views/layouts/app.blade.php) {"exception":"[object] (ErrorException(code: 0): Return value of GeneaLabs\\LaravelModelCaching\\CacheKey::getValuesFromWhere() must be of the type string, array returned (View: /home/user/sites/site.php/www/resources/views/layouts/app.blade.php) (View: /home/user/sites/site.php/www/resources/views/layouts/app.blade.php) at /home/user/sites/site.php/www/vendor/genealabs/laravel-model-caching/src/CacheKey.php:139, ErrorException(code: 0): Return value of GeneaLabs\\LaravelModelCaching\\CacheKey::getValuesFromWhere() must be of the type string, array returned (View: /home/user/sites/site.php/www/resources/views/layouts/app.blade.php) at /home/user/sites/site.php/www/vendor/genealabs/laravel-model-caching/src/CacheKey.php:139, Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of GeneaLabs\\LaravelModelCaching\\CacheKey::getValuesFromWhere() must be of the type string, array returned at /home/user/sites/site.php/www/vendor/genealabs/laravel-model-caching/src/CacheKey.php:139)
```

The query that is causing this will help us identify what is going on.
