### ISSUE TITLE
Return value of GeneaLabs\LaravelModelCaching\CacheKey::getValuesFromWhere() must be of the type string, array returned

### ISSUE THREAD

**Issue by zhenyangze** [GeneaLabs/laravel-model-caching#203]
**Describe the bug**
Return value of GeneaLabs\LaravelModelCaching\CacheKey::getValuesFromWhere() must be of the type string, array returned

**Eloquent Query**
Please provide the complete eloquent query that caused the bug, for example:
```php
$model->where('id', [1])->get();
```

**Stack Trace**
```php
[2019-01-19 16:53:50] product.ERROR: Type error: Return value of GeneaLabs\LaravelModelCaching\CacheKey::getValuesFromWhere() must be of the type string, array returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Return value of GeneaLabs\\LaravelModelCaching\\CacheKey::getValuesFromWhere() must be of the type string, array returned at /home/wwwroot//vendor/genealabs/laravel-model-caching/src/CacheKey.php:139)
[stacktrace]
#0 /home/wwwroot//vendor/genealabs/laravel-model-caching/src/CacheKey.php(113): GeneaLabs\\LaravelModelCaching\\CacheKey->getValuesFromWhere(Array)
#1 /home/wwwroot//vendor/genealabs/laravel-model-caching/src/CacheKey.php(263): GeneaLabs\\LaravelModelCaching\\CacheKey->getValuesClause(Array)
#2 /home/wwwroot//vendor/genealabs/laravel-model-caching/src/CacheKey.php(167): GeneaLabs\\LaravelModelCaching\\CacheKey->getOtherClauses(Array, '-university_sch...')
#3 [internal function]: GeneaLabs\\LaravelModelCaching\\CacheKey->GeneaLabs\\LaravelModelCaching\\{closure}('-university_sch...', Array)
#4 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Support/Collection.php(1228): array_reduce(Array, Object(Closure), NULL)
#5 /home/wwwroot//vendor/genealabs/laravel-model-caching/src/CacheKey.php(170): Illuminate\\Support\\Collection->reduce(Object(Closure))
#6 /home/wwwroot//vendor/genealabs/laravel-model-caching/src/CacheKey.php(36): GeneaLabs\\LaravelModelCaching\\CacheKey->getWhereClauses()
#7 /home/wwwroot//vendor/genealabs/laravel-model-caching/src/Traits/Caching.php(76): GeneaLabs\\LaravelModelCaching\\CacheKey->make(Array, NULL, '')
#8 /home/wwwroot//vendor/genealabs/laravel-model-caching/src/CachedBuilder.php(78): GeneaLabs\\LaravelModelCaching\\CachedBuilder->makeCacheKey(Array)
#9 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(154): GeneaLabs\\LaravelModelCaching\\CachedBuilder->get(Array)
#10 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(143): Illuminate\\Database\\Eloquent\\Relations\\Relation->get()
#11 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(529): Illuminate\\Database\\Eloquent\\Relations\\Relation->getEager()
#12 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(498): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelation(Array, 'universitySchoo...', Object(Closure))
#13 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(466): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelations(Array)
#14 /home/wwwroot//app/Modules/Cee/Services/AssistantServices.php(94): Illuminate\\Database\\Eloquent\\Builder->get()
#15 /home/wwwroot//app/Modules/Cee/Services/AssistantServices.php(50): App\\Modules\\Cee\\Services\\AssistantServices->getSchoolList()
#16 /home/wwwroot//app/Modules/Cee/Http/Controllers/MajorController.php(226): App\\Modules\\Cee\\Services\\AssistantServices->getResult()
#17 /home/wwwroot//app/Modules/Cee/Http/Controllers/MajorController.php(118): App\\Modules\\Cee\\Http\\Controllers\\MajorController->getCeeReport(Array)
#18 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Cache/Repository.php(327): App\\Modules\\Cee\\Http\\Controllers\\MajorController->App\\Modules\\Cee\\Http\\Controllers\\{closure}()
#19 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(304): Illuminate\\Cache\\Repository->remember('cee_major_repor...', 720, Object(Closure))
#20 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#21 /home/wwwroot//app/Modules/Cee/Http/Controllers/MajorController.php(119): Illuminate\\Support\\Facades\\Facade::__callStatic('remember', Array)
#22 [internal function]: App\\Modules\\Cee\\Http\\Controllers\\MajorController->apiReport(Object(Illuminate\\Http\\Request))
#23 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#24 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('apiReport', Array)
#25 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Modules\\Cee\\Http\\Controllers\\MajorController), 'apiReport')
#26 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#27 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#28 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 500, '1')
#34 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#38 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#39 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#40 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#41 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/wwwroot//vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/wwwroot//app/Http/Middleware/RedirectToRootWithOutphp.php(22): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\RedirectToRootWithOutphp->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#62 /home/wwwroot//vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#63 /home/wwwroot//vendor/swooletw/laravel-swoole/src/Server/Sandbox.php(232): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#64 /home/wwwroot//vendor/swooletw/laravel-swoole/src/Server/Sandbox.php(193): SwooleTW\\Http\\Server\\Sandbox->handleRequest(Object(Illuminate\\Http\\Request))
#65 /home/wwwroot//vendor/swooletw/laravel-swoole/src/Server/Sandbox.php(159): SwooleTW\\Http\\Server\\Sandbox->prepareObResponse(Object(Illuminate\\Http\\Request))
#66 /home/wwwroot//vendor/swooletw/laravel-swoole/src/Server/Manager.php(196): SwooleTW\\Http\\Server\\Sandbox->run(Object(Illuminate\\Http\\Request))
#67 {main}
"}
```

**Environment**
 - PHP: [e.g. 7.1.0]
 - OS: [e.g. Ubuntu 18.04]
 - Laravel: [e.g. 5.6.15]
 - Model Caching: [e.g. 0.2.61]

**Additional context**
error file is : vendor/genealabs/laravel-model-caching/src/CacheKey.php
```php
        if (is_array(array_get($where, "values"))) {
            return implode("_", $where["values"]);
        }
```
Laravel support both where('id', [1]) and where('id', 1);
when use where('id', 1), the $where will show:
```php
array:5 [▼
  "type" => "Basic"
  "column" => "id"
  "operator" => "="
  "value" => 1,
  "boolean" => "and"
]
```
when use where('id', [1]), the $where will show:
```php
array:5 [▼
  "type" => "Basic"
  "column" => "id"
  "operator" => "="
  "value" => array:1 [▼
    0 => 1
  ]
  "boolean" => "and"
]
```
so may be support both: add values and value convert to string;

**Comment by zhenyangze** [comment]
```php
        if (is_array(array_get($where, "values"))) {
            return implode("_", $where["values"]);
        }

        if (is_array(array_get($where, "value"))) {
            return reset($where['value']);
        }
```

**Comment by zhenyangze** [comment]
More: model()->find(1) and model()->find([1]) Error:
edit file `vendor/genealabs/laravel-model-caching/src/CachedBuilder.php`
search  'find' function like that
```php
    /**
     * @SuppressWarnings(PHPMD.ShortVariable)
     */
    public function find($id, $columns = ["*"])
    {
        if (! $this->isCachable()) {
            return parent::find($id, $columns);
        }

        $idKey = collect($id)->implode('-');
        $preStr = is_array($id) ? 'find-list' : 'find';
        $cacheKey = $this->makeCacheKey($columns, null, "-" . $preStr . "_{$idKey}");

        return $this->cachedValue(func_get_args(), $cacheKey);
    }
```

**Comment by mikebronner** [comment]
Please provide the full stack trace of the error. I am currently traveling and won't be back until next week.

**Comment by zhenyangze** [comment]
Have a nice trip;I'll add it later.

**Comment by zhenyangze** [comment]
already provide the full stack trace of the error.
and the second bug report goto this page: https://github.com/GeneaLabs/laravel-model-caching/issues/204

**Comment by zhenyangze** [comment]
> More: model()->find(1) and model()->find([1]) Error:
> edit file `vendor/genealabs/laravel-model-caching/src/CachedBuilder.php`
> change `find` function like that
> 
> ```
>     /**
>      * @SuppressWarnings(PHPMD.ShortVariable)
>      */
>     public function find($id, $columns = ["*"])
>     {
>         if (! $this->isCachable()) {
>             return parent::find($id, $columns);
>         }
> 
>         $idKey = collect($id)->implode('-');
>         $preStr = is_array($id) ? 'find-list' : 'find';
>         $cacheKey = $this->makeCacheKey($columns, null, "-" . $preStr . "_{$idKey}");
> 
>         return $this->cachedValue(func_get_args(), $cacheKey);
>     }
> ```

https://github.com/GeneaLabs/laravel-model-caching/issues/204

**Comment by cluebattery** [comment]
@mikebronner can confirm that @zhenyangze's proposed change does fix the issue as I ran into this last night when attempting to utilize this package. 

I ran into the issue with the following:

```
private function getEvent($hash)
    {
        $event = Hashids::decode($hash);
        return Event::where('id', $event[0])->first();
    }
```

Working on a proper pull request for you at the moment.

**Comment by cluebattery** [comment]
https://github.com/GeneaLabs/laravel-model-caching/pull/214

**Comment by mikebronner** [comment]
@zhenyangze  @cluebattery Can you guys test this again with the latest release, 0.4.12? Please re-open if it is still failing.
