### ISSUE TITLE
Call to undefined method Illuminate\Events\Dispatcher::fire()

### ISSUE THREAD

**Issue by DavidSprauel** [GeneaLabs/laravel-model-caching#235]
I encountered a weird error since I updated my composer today. I'm executing a migration and got the `Call to undefined method Illuminate\Events\Dispatcher::fire()` when my model boot.
I only get the error when i `use Cachable`.

Here is the query i'm doing.
```php
$journeys = JourneyModel::whereNotNull('photo')->get();
```
I have a BaseModel which is the parent of all my model and I `use Cachable` in this model.

Here is the stack trace
```
[2019-04-09 08:34:37] local.ERROR: Call to undefined method Illuminate\Events\Dispatcher::fire() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Illuminate\\Events\\Dispatcher::fire() at /var/www/dev-team/dsprauel/api-unleashed/vendor/fico7489/laravel-pivot/src/Traits/ExtendFireModelEventTrait.php:36)
[stacktrace]
#0 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(184): Api\\Models\\Entities\\Eloquent\\BaseModel->fireModelEvent('booting', false)
#1 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(165): Illuminate\\Database\\Eloquent\\Model->bootIfNotBooted()
#2 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1628): Illuminate\\Database\\Eloquent\\Model->__construct()
#3 /var/www/dev-team/dsprauel/api-unleashed/database/migrations/2019_04_04_140408_create_thumbnail_for_journey_pictures.php(12): Illuminate\\Database\\Eloquent\\Model::__callStatic('whereNotNull', Array)
#4 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(360): CreateThumbnailForJourneyPictures->up()
#5 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(367): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#6 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(178): Illuminate\\Database\\Migrations\\Migrator->runMigration(Object(CreateThumbnailForJourneyPictures), 'up')
#7 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(147): Illuminate\\Database\\Migrations\\Migrator->runUp('/var/www/dev-te...', 178, false)
#8 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(96): Illuminate\\Database\\Migrations\\Migrator->runPending(Array, Array)
#9 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(71): Illuminate\\Database\\Migrations\\Migrator->run(Array, Array)
#10 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#11 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#12 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#14 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Container/Container.php(580): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#15 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#16 /var/www/dev-team/dsprauel/api-unleashed/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#17 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 /var/www/dev-team/dsprauel/api-unleashed/vendor/symfony/console/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/dev-team/dsprauel/api-unleashed/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Migrations\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/dev-team/dsprauel/api-unleashed/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/www/dev-team/dsprauel/api-unleashed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /var/www/dev-team/dsprauel/api-unleashed/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 {main}
"}
```

**Environment**
 - PHP: 7.1.25
 - OS: ubuntu 16.04
 - Laravel: 5.8.10
 - Model Caching: 0.4.13

**Comment by mikebronner** [comment]
This looks like it still has an old version of Laravel-pivot installed. I would recommend deleting your `vendor` folder, clearing composer cache, and re-updating:
```sh
rm -rf vendor
composer cache-clear
composer update
```

Let me know if that works.

**Comment by DavidSprauel** [comment]
Worked like a charm. Thanks
